name: CI

on:
  push:
    paths:
      - '**.php'
      - 'phpcs.xml'
      - 'test/phpmd/ruleset.xml'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**.php'
      - 'phpcs.xml'
      - 'test/phpmd/ruleset.xml'
      - '.github/workflows/**'

jobs:
  php-code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer
          composer --version 

      - name: Install Dependencies
        run: |
          composer install --dev 
        continue-on-error: true

      - name: Check PHPStan installation
        run: |
          composer show phpstan/phpstan
        continue-on-error: true

      - name: Run PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --standard=phpcs.xml --extensions=php bin lib index.php
        continue-on-error: true

      - name: Run PHP Mess Detector
        uses: php-actions/phpmd@v1
        with:
          php_version: 8.1
          path: bin,lib,index.php
          output: text
          ruleset: test/phpmd/ruleset.xml
        continue-on-error: true

      - name: Run PHPStan
        run: |
          vendor/bin/phpstan analyse bin lib 
        continue-on-error: true

