name: Run PHPUnit Tests and Generate Coverage Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Install Composer dependencies
      run: composer install

    - name: Run PHPUnit tests and generate Cobertura coverage report
      uses: php-actions/phpunit@v3
      with:
        php_version: '8.2'
        version: '9.6.11'
        configuration: 'phpunit.xml'
        php_extensions: 'pdo mbstring xml curl sqlite3 pdo-sqlite gd xdebug'
        coverage_cobertura: 'log/coverage-cobertura.xml'

      env:
        XDEBUG_MODE: coverage

    - name: Generate Coverage Summary in Markdown
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: log/coverage-cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '50 75'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
