name: Run PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  

    - name: Install Composer dependencies
      run: composer install

    - name: Run PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        php_version: '8.2'  
        version: 'latest'  
        configuration: 'phpunit.xml'  
        php_extensions: 'pdo mbstring xml curl sqlite3 pdo-sqlite gd' 
        coverage_html: 'coverage/report.html'  
